CREATE TABLE country (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'Numeric autoincremental id',
  name VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Country name',
  standardCode VARCHAR(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Country standard code',
  language VARCHAR(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Country standard language code')
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE country ADD CONSTRAINT fk_language FOREIGN KEY (language) REFERENCES language(code) ON DELETE CASCADE;

INSERT INTO country (name, standardCode, language) values ('Aruba','AW','nl');
INSERT INTO country (name, standardCode, language) values ('Afghanistan','AF','ps');
INSERT INTO country (name, standardCode, language) values ('Angola','AO','pt');
INSERT INTO country (name, standardCode, language) values ('Anguilla','AI','en');
INSERT INTO country (name, standardCode, language) values ('Aland Islands','AX','sv');
INSERT INTO country (name, standardCode, language) values ('Albania','AL','sq');
INSERT INTO country (name, standardCode, language) values ('Andorra','AD','ca');
INSERT INTO country (name, standardCode, language) values ('United Arab Emirates','AE','ar');
INSERT INTO country (name, standardCode, language) values ('Argentina','AR','es');
INSERT INTO country (name, standardCode, language) values ('Armenia','AM','ru');
INSERT INTO country (name, standardCode, language) values ('American Samoa','AS','en');
INSERT INTO country (name, standardCode, language) values ('French Southern and Antarctic Lands','TF','fr');
INSERT INTO country (name, standardCode, language) values ('Antigua and Barbuda','AG','en');
INSERT INTO country (name, standardCode, language) values ('Australia','AU','en');
INSERT INTO country (name, standardCode, language) values ('Austria','AT','de');
INSERT INTO country (name, standardCode, language) values ('Azerbaijan','AZ','ru');
INSERT INTO country (name, standardCode, language) values ('Burundi','BI','fr');
INSERT INTO country (name, standardCode, language) values ('Belgium','BE','fr');
INSERT INTO country (name, standardCode, language) values ('Benin','BJ','fr');
INSERT INTO country (name, standardCode, language) values ('Burkina Faso','BF','fr');
INSERT INTO country (name, standardCode, language) values ('Bangladesh','BD','bn');
INSERT INTO country (name, standardCode, language) values ('Bulgaria','BG','bg');
INSERT INTO country (name, standardCode, language) values ('Bahrain','BH','ar');
INSERT INTO country (name, standardCode, language) values ('Bahamas','BS','en');
INSERT INTO country (name, standardCode, language) values ('Bosnia and Herzegovina','BA','hr');
INSERT INTO country (name, standardCode, language) values ('Saint Barthélemy','BL','fr');
INSERT INTO country (name, standardCode, language) values ('Belarus','BY','ru');
INSERT INTO country (name, standardCode, language) values ('Belize','BZ','es');
INSERT INTO country (name, standardCode, language) values ('Bermuda','BM','en');
INSERT INTO country (name, standardCode, language) values ('Bolivia','BO','es');
INSERT INTO country (name, standardCode, language) values ('Brazil','BR','pt');
INSERT INTO country (name, standardCode, language) values ('Barbados','BB','en');
INSERT INTO country (name, standardCode, language) values ('Brunei','BN','ms');
INSERT INTO country (name, standardCode, language) values ('Bhutan','BT','dz');
INSERT INTO country (name, standardCode, language) values ('Bouvet Island','BV','no');
INSERT INTO country (name, standardCode, language) values ('Botswana','BW','en');
INSERT INTO country (name, standardCode, language) values ('Central African Republic','CF','fr');
INSERT INTO country (name, standardCode, language) values ('Canada','CA','en');
INSERT INTO country (name, standardCode, language) values ('Cocos (Keeling) Islands','CC','en');
INSERT INTO country (name, standardCode, language) values ('Switzerland','CH','it');
INSERT INTO country (name, standardCode, language) values ('Chile','CL','es');
INSERT INTO country (name, standardCode, language) values ('China','CN','zh');
INSERT INTO country (name, standardCode, language) values ('Ivory Coast','CI','fr');
INSERT INTO country (name, standardCode, language) values ('Cameroon','CM','fr');
INSERT INTO country (name, standardCode, language) values ('DR Congo','CD','fr');
INSERT INTO country (name, standardCode, language) values ('Republic of the Congo','CG','fr');
INSERT INTO country (name, standardCode, language) values ('Cook Islands','CK','en');
INSERT INTO country (name, standardCode, language) values ('Colombia','CO','es');
INSERT INTO country (name, standardCode, language) values ('Comoros','KM','fr');
INSERT INTO country (name, standardCode, language) values ('Cape Verde','CV','pt');
INSERT INTO country (name, standardCode, language) values ('Costa Rica','CR','es');
INSERT INTO country (name, standardCode, language) values ('Cuba','CU','es');
INSERT INTO country (name, standardCode, language) values ('Curaçao','CW','nl');
INSERT INTO country (name, standardCode, language) values ('Christmas Island','CX','en');
INSERT INTO country (name, standardCode, language) values ('Cayman Islands','KY','en');
INSERT INTO country (name, standardCode, language) values ('Cyprus','CY','el');
INSERT INTO country (name, standardCode, language) values ('Czech Republic','CZ','sk');
INSERT INTO country (name, standardCode, language) values ('Germany','DE','de');
INSERT INTO country (name, standardCode, language) values ('Djibouti','DJ','fr');
INSERT INTO country (name, standardCode, language) values ('Dominica','DM','en');
INSERT INTO country (name, standardCode, language) values ('Denmark','DK','da');
INSERT INTO country (name, standardCode, language) values ('Dominican Republic','DO','es');
INSERT INTO country (name, standardCode, language) values ('Algeria','DZ','ar');
INSERT INTO country (name, standardCode, language) values ('Ecuador','EC','es');
INSERT INTO country (name, standardCode, language) values ('Egypt','EG','ar');
INSERT INTO country (name, standardCode, language) values ('Eritrea','ER','en');
INSERT INTO country (name, standardCode, language) values ('Western Sahara','EH','es');
INSERT INTO country (name, standardCode, language) values ('Spain','ES','es');
INSERT INTO country (name, standardCode, language) values ('Estonia','EE','et');
INSERT INTO country (name, standardCode, language) values ('Ethiopia','ET','am');
INSERT INTO country (name, standardCode, language) values ('Finland','FI','sv');
INSERT INTO country (name, standardCode, language) values ('Fiji','FJ','en');
INSERT INTO country (name, standardCode, language) values ('Falkland Islands','FK','en');
INSERT INTO country (name, standardCode, language) values ('France','FR','fr');
INSERT INTO country (name, standardCode, language) values ('Faroe Islands','FO','fo');
INSERT INTO country (name, standardCode, language) values ('Micronesia','FM','en');
INSERT INTO country (name, standardCode, language) values ('Gabon','GA','fr');
INSERT INTO country (name, standardCode, language) values ('United Kingdom','GB','en');
INSERT INTO country (name, standardCode, language) values ('Georgia','GE','ka');
INSERT INTO country (name, standardCode, language) values ('Guernsey','GG','fr');
INSERT INTO country (name, standardCode, language) values ('Ghana','GH','en');
INSERT INTO country (name, standardCode, language) values ('Gibraltar','GI','en');
INSERT INTO country (name, standardCode, language) values ('Guinea','GN','fr');
INSERT INTO country (name, standardCode, language) values ('Guadeloupe','GP','fr');
INSERT INTO country (name, standardCode, language) values ('Gambia','GM','en');
INSERT INTO country (name, standardCode, language) values ('Guinea-Bissau','GW','pt');
INSERT INTO country (name, standardCode, language) values ('Equatorial Guinea','GQ','fr');
INSERT INTO country (name, standardCode, language) values ('Greece','GR','el');
INSERT INTO country (name, standardCode, language) values ('Grenada','GD','en');
INSERT INTO country (name, standardCode, language) values ('Greenland','GL','kl');
INSERT INTO country (name, standardCode, language) values ('Guatemala','GT','es');
INSERT INTO country (name, standardCode, language) values ('French Guiana','GF','fr');
INSERT INTO country (name, standardCode, language) values ('Guam','GU','en');
INSERT INTO country (name, standardCode, language) values ('Guyana','GY','en');
INSERT INTO country (name, standardCode, language) values ('Hong Kong','HK','en');
INSERT INTO country (name, standardCode, language) values ('Heard Island and McDonald Islands','HM','en');
INSERT INTO country (name, standardCode, language) values ('Honduras','HN','es');
INSERT INTO country (name, standardCode, language) values ('Croatia','HR','hr');
INSERT INTO country (name, standardCode, language) values ('Haiti','HT','fr');
INSERT INTO country (name, standardCode, language) values ('Hungary','HU','hu');
INSERT INTO country (name, standardCode, language) values ('Indonesia','ID','id');
INSERT INTO country (name, standardCode, language) values ('Isle of Man','IM','en');
INSERT INTO country (name, standardCode, language) values ('India','IN','en');
INSERT INTO country (name, standardCode, language) values ('British Indian Ocean Territory','IO','en');
INSERT INTO country (name, standardCode, language) values ('Ireland','IE','en');
INSERT INTO country (name, standardCode, language) values ('Iran','IR','fa');
INSERT INTO country (name, standardCode, language) values ('Iraq','IQ','ar');
INSERT INTO country (name, standardCode, language) values ('Iceland','IS','is');
INSERT INTO country (name, standardCode, language) values ('Israel','IL','ar');
INSERT INTO country (name, standardCode, language) values ('Italy','IT','it');
INSERT INTO country (name, standardCode, language) values ('Jamaica','JM','en');
INSERT INTO country (name, standardCode, language) values ('Jersey','JE','en');
INSERT INTO country (name, standardCode, language) values ('Jordan','JO','ar');
INSERT INTO country (name, standardCode, language) values ('Japan','JP','ja');
INSERT INTO country (name, standardCode, language) values ('Kazakhstan','KZ','ru');
INSERT INTO country (name, standardCode, language) values ('Kenya','KE','en');
INSERT INTO country (name, standardCode, language) values ('Kyrgyzstan','KG','ru');
INSERT INTO country (name, standardCode, language) values ('Cambodia','KH','km');
INSERT INTO country (name, standardCode, language) values ('Kiribati','KI','en');
INSERT INTO country (name, standardCode, language) values ('Saint Kitts and Nevis','KN','en');
INSERT INTO country (name, standardCode, language) values ('South Korea','KR','ko');
INSERT INTO country (name, standardCode, language) values ('Kosovo','XK','sr');
INSERT INTO country (name, standardCode, language) values ('Kuwait','KW','ar');
INSERT INTO country (name, standardCode, language) values ('Laos','LA','lo');
INSERT INTO country (name, standardCode, language) values ('Lebanon','LB','ar');
INSERT INTO country (name, standardCode, language) values ('Liberia','LR','en');
INSERT INTO country (name, standardCode, language) values ('Libya','LY','ar');
INSERT INTO country (name, standardCode, language) values ('Saint Lucia','LC','en');
INSERT INTO country (name, standardCode, language) values ('Liechtenstein','LI','de');
INSERT INTO country (name, standardCode, language) values ('Sri Lanka','LK','si');
INSERT INTO country (name, standardCode, language) values ('Lesotho','LS','en');
INSERT INTO country (name, standardCode, language) values ('Lithuania','LT','lt');
INSERT INTO country (name, standardCode, language) values ('Luxembourg','LU','fr');
INSERT INTO country (name, standardCode, language) values ('Latvia','LV','lv');
INSERT INTO country (name, standardCode, language) values ('Macau','MO','zh');
INSERT INTO country (name, standardCode, language) values ('Saint Martin','MF','fr');
INSERT INTO country (name, standardCode, language) values ('Morocco','MA','ar');
INSERT INTO country (name, standardCode, language) values ('Monaco','MC','fr');
INSERT INTO country (name, standardCode, language) values ('Moldova','MD','ro');
INSERT INTO country (name, standardCode, language) values ('Madagascar','MG','fr');
INSERT INTO country (name, standardCode, language) values ('Maldives','MV','dv');
INSERT INTO country (name, standardCode, language) values ('Mexico','MX','es');
INSERT INTO country (name, standardCode, language) values ('Marshall Islands','MH','en');
INSERT INTO country (name, standardCode, language) values ('Macedonia','MK','mk');
INSERT INTO country (name, standardCode, language) values ('Mali','ML','fr');
INSERT INTO country (name, standardCode, language) values ('Malta','MT','en');
INSERT INTO country (name, standardCode, language) values ('Myanmar','MM','my');
INSERT INTO country (name, standardCode, language) values ('Montenegro','ME','sr');
INSERT INTO country (name, standardCode, language) values ('Mongolia','MN','mn');
INSERT INTO country (name, standardCode, language) values ('Northern Mariana Islands','MP','en');
INSERT INTO country (name, standardCode, language) values ('Mozambique','MZ','pt');
INSERT INTO country (name, standardCode, language) values ('Mauritania','MR','ar');
INSERT INTO country (name, standardCode, language) values ('Montserrat','MS','en');
INSERT INTO country (name, standardCode, language) values ('Martinique','MQ','fr');
INSERT INTO country (name, standardCode, language) values ('Mauritius','MU','fr');
INSERT INTO country (name, standardCode, language) values ('Malawi','MW','en');
INSERT INTO country (name, standardCode, language) values ('Malaysia','MY','en');
INSERT INTO country (name, standardCode, language) values ('Mayotte','YT','fr');
INSERT INTO country (name, standardCode, language) values ('Namibia','NA','de');
INSERT INTO country (name, standardCode, language) values ('New Caledonia','NC','fr');
INSERT INTO country (name, standardCode, language) values ('Niger','NE','fr');
INSERT INTO country (name, standardCode, language) values ('Norfolk Island','NF','en');
INSERT INTO country (name, standardCode, language) values ('Nigeria','NG','en');
INSERT INTO country (name, standardCode, language) values ('Nicaragua','NI','es');
INSERT INTO country (name, standardCode, language) values ('Niue','NU','en');
INSERT INTO country (name, standardCode, language) values ('Netherlands','NL','nl');
INSERT INTO country (name, standardCode, language) values ('Norway','NO','nn');
INSERT INTO country (name, standardCode, language) values ('Nepal','NP','ne');
INSERT INTO country (name, standardCode, language) values ('Nauru','NR','en');
INSERT INTO country (name, standardCode, language) values ('New Zealand','NZ','en');
INSERT INTO country (name, standardCode, language) values ('Oman','OM','ar');
INSERT INTO country (name, standardCode, language) values ('Pakistan','PK','en');
INSERT INTO country (name, standardCode, language) values ('Panama','PA','es');
INSERT INTO country (name, standardCode, language) values ('Pitcairn Islands','PN','en');
INSERT INTO country (name, standardCode, language) values ('Peru','PE','es');
INSERT INTO country (name, standardCode, language) values ('Philippines','PH','en');
INSERT INTO country (name, standardCode, language) values ('Palau','PW','en');
INSERT INTO country (name, standardCode, language) values ('Papua New Guinea','PG','en');
INSERT INTO country (name, standardCode, language) values ('Poland','PL','pl');
INSERT INTO country (name, standardCode, language) values ('Puerto Rico','PR','en');
INSERT INTO country (name, standardCode, language) values ('North Korea','KP','ko');
INSERT INTO country (name, standardCode, language) values ('Portugal','PT','pt');
INSERT INTO country (name, standardCode, language) values ('Paraguay','PY','es');
INSERT INTO country (name, standardCode, language) values ('Palestine','PS','ar');
INSERT INTO country (name, standardCode, language) values ('French Polynesia','PF','fr');
INSERT INTO country (name, standardCode, language) values ('Qatar','QA','ar');
INSERT INTO country (name, standardCode, language) values ('Réunion','RE','fr');
INSERT INTO country (name, standardCode, language) values ('Romania','RO','ro');
INSERT INTO country (name, standardCode, language) values ('Russia','RU','ru');
INSERT INTO country (name, standardCode, language) values ('Rwanda','RW','fr');
INSERT INTO country (name, standardCode, language) values ('Saudi Arabia','SA','ar');
INSERT INTO country (name, standardCode, language) values ('Sudan','SD','en');
INSERT INTO country (name, standardCode, language) values ('Senegal','SN','fr');
INSERT INTO country (name, standardCode, language) values ('Singapore','SG','en');
INSERT INTO country (name, standardCode, language) values ('South Georgia','GS','en');
INSERT INTO country (name, standardCode, language) values ('Svalbard and Jan Mayen','SJ','no');
INSERT INTO country (name, standardCode, language) values ('Solomon Islands','SB','en');
INSERT INTO country (name, standardCode, language) values ('Sierra Leone','SL','en');
INSERT INTO country (name, standardCode, language) values ('El Salvador','SV','es');
INSERT INTO country (name, standardCode, language) values ('San Marino','SM','it');
INSERT INTO country (name, standardCode, language) values ('Somalia','SO','ar');
INSERT INTO country (name, standardCode, language) values ('Saint Pierre and Miquelon','PM','fr');
INSERT INTO country (name, standardCode, language) values ('Serbia','RS','sr');
INSERT INTO country (name, standardCode, language) values ('South Sudan','SS','en');
INSERT INTO country (name, standardCode, language) values ('São Tomé and Príncipe','ST','pt');
INSERT INTO country (name, standardCode, language) values ('Suriname','SR','nl');
INSERT INTO country (name, standardCode, language) values ('Slovakia','SK','sk');
INSERT INTO country (name, standardCode, language) values ('Slovenia','SI','sl');
INSERT INTO country (name, standardCode, language) values ('Sweden','SE','sv');
INSERT INTO country (name, standardCode, language) values ('Swaziland','SZ','en');
INSERT INTO country (name, standardCode, language) values ('Sint Maarten','SX','en');
INSERT INTO country (name, standardCode, language) values ('Seychelles','SC','fr');
INSERT INTO country (name, standardCode, language) values ('Syria','SY','ar');
INSERT INTO country (name, standardCode, language) values ('Turks and Caicos Islands','TC','en');
INSERT INTO country (name, standardCode, language) values ('Chad','TD','ar');
INSERT INTO country (name, standardCode, language) values ('Togo','TG','fr');
INSERT INTO country (name, standardCode, language) values ('Thailand','TH','th');
INSERT INTO country (name, standardCode, language) values ('Tajikistan','TJ','tg');
INSERT INTO country (name, standardCode, language) values ('Tokelau','TK','en');
INSERT INTO country (name, standardCode, language) values ('Turkmenistan','TM','tk');
INSERT INTO country (name, standardCode, language) values ('Tonga','TO','en');
INSERT INTO country (name, standardCode, language) values ('Trinidad and Tobago','TT','en');
INSERT INTO country (name, standardCode, language) values ('Tunisia','TN','ar');
INSERT INTO country (name, standardCode, language) values ('Turkey','TR','tr');
INSERT INTO country (name, standardCode, language) values ('Tuvalu','TV','en');
INSERT INTO country (name, standardCode, language) values ('Taiwan','TW','zh');
INSERT INTO country (name, standardCode, language) values ('Tanzania','TZ','en');
INSERT INTO country (name, standardCode, language) values ('Uganda','UG','en');
INSERT INTO country (name, standardCode, language) values ('Ukraine','UA','uk');
INSERT INTO country (name, standardCode, language) values ('United States Minor Outlying Islands','UM','en');
INSERT INTO country (name, standardCode, language) values ('Uruguay','UY','es');
INSERT INTO country (name, standardCode, language) values ('United States','US','en');
INSERT INTO country (name, standardCode, language) values ('Uzbekistan','UZ','uz');
INSERT INTO country (name, standardCode, language) values ('Vatican City','VA','it');
INSERT INTO country (name, standardCode, language) values ('Saint Vincent and the Grenadines','VC','en');
INSERT INTO country (name, standardCode, language) values ('Venezuela','VE','es');
INSERT INTO country (name, standardCode, language) values ('British Virgin Islands','VG','en');
INSERT INTO country (name, standardCode, language) values ('United States Virgin Islands','VI','en');
INSERT INTO country (name, standardCode, language) values ('Vietnam','VN','vi');
INSERT INTO country (name, standardCode, language) values ('Vanuatu','VU','en');
INSERT INTO country (name, standardCode, language) values ('Wallis and Futuna','WF','fr');
INSERT INTO country (name, standardCode, language) values ('Samoa','WS','en');
INSERT INTO country (name, standardCode, language) values ('Yemen','YE','ar');
INSERT INTO country (name, standardCode, language) values ('South Africa','ZA','en');
INSERT INTO country (name, standardCode, language) values ('Zambia','ZM','en');
INSERT INTO country (name, standardCode, language) values ('Zimbabwe','ZW','en');